### ISSUE TITLE
backport it to older versions

### ISSUE THREAD

**Issue by perdakovich** [Lortseam/sneak-tweak#5]
I would like to have smooth sneaking enabled for versions older than 1.16

**Comment by Lortseam** [comment]
I won't do that, just use the latest version.

**Comment by perdakovich** [comment]
understandable, have a great day

**Comment by Nixuge** [comment]
@goosegit11 mod has some broken things so may play w it a bit, do you still need it? What version would you need specifically?

**Comment by perdakovich** [comment]
First of all I would like to say that I don't need it that much anymore, so if it takes a lot of time for you then it's _really_ not worth it. but if you want to tinker with it, then go ahead


> What version would you need specifically?

1.8.9

> Do you still need it?

not really, i just accepted it and am currently playing on 1.18.2.

my problem with 1.18.2 is that you can't block on 1.8 pvp servers like hypixel. there's a compatibility layer, so blocking with a sword is displayed as a shield. sorry, i'm not a native speaker, can't explain it clearly, but if you played on hypixel, you'll understand it.
I like 1.18.2 better, but because of this problem I would like to use 1.8.9 with proper sword blocking.

Anyway, one of the things I can't play without on 1.8.9 is smooth sneaking. I don't need any settings or customizability for sneaking, I just need sneaking from 1.16.
