### ISSUE TITLE
F5 mode sneaking height and general sneaking height too low

### ISSUE THREAD

**Issue by ItsPasi** [Lortseam/sneak-tweak#7]
If you go into F5 mode, the setting "increase sneaking height" does not affect the view. Also this same setting still doesn't reduce height to what was normal in older versions, Combining this setting with "no sneaking animation" will make sneak spamming look way too distracting. I would appreciate an option to either change the height manually or just update the mod to have less height impact with that setting on.

**Comment by Lortseam** [comment]
I have added some more config options in the latest release 1.10.0.
